<?php
	echo $this->doctype();
?>
<html>
<head>

<base href="<?php echo $this->serverUrl($this->baseUrl('/')); ?>" />

<?php
	echo $this->headMeta();
    echo $this->headTitle();
	echo $this->headLink()
                ->prependStylesheet('/lib/dijit/themes/claro/claro.css', 'screen')
                ->headLink()
                ->appendStylesheet('/skins/' . Zend_Registry::get('skinName') . '/style.css', 'screen');
?>
<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:700,300' rel='stylesheet' type='text/css'/>
<script>
dojoConfig = {
	async: true,
	parseOnLoad: true,
	dojoBlankHtmlUrl: "/lib/dojo/resources/blank.html",
	ioPublish: true,
	has: {
       "dojo-firebug": true,
       "dojo-debug-messages": true
	},
	packages: [
	     {
	    	 name: "aurora",
	         location: "/lib/aurora"
	     }
	],
	app: {

	},
	// Get "fresh" resources
	cacheBust: true
};
</script>
<script src="//ajax.googleapis.com/ajax/libs/dojo/1.9.1/dojo/dojo.js"></script>
<script type="text/javascript">
require([
	"aurora/app",
]);
</script>
</head>
<body class="claro">
	<div data-dojo-type="dijit/layout/LayoutContainer" data-dojo-props="design: 'headline', gutters: 'false'" style="z-index: 0; width: 100%; height: 100%;">
	<div data-dojo-id="bodyContentPanel" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', spliter: 'false'" style="padding: 0; margin: 0;"> 
		<div id="header" data-dojo-id="header" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', splitter: 'false'">
				<div id="header-container">
				

					<img style="position: relative; top: 10px; z-index: 99;" src="<?php echo '/skins/' . Zend_Registry::get('skinName') . '/images/logo.png';?>">
					<div class="social-icons">
						<a class="social search" href="#">Search</a>
						<a class="social twitter" href="<?php echo $this->appSettings->twitterUrl; ?>">Twitter</a>
						<a class="social facebook" href="<?php echo $this->appSettings->facebookUrl; ?>">Facebook</a>
					</div> <!-- end of social -->
					
					<!--<div id="headerphoto">-->
					<div id="headerphoto-overlay">
						<?php 
							echo '<img src="' . $this->baseUrl('/') . 'skins/fypg/images/headerphoto-overlay.png" alt="photo" height="524" width="851" />'; 
						?>
					</div> <!-- end of headerphoto-overlay -->
					<!--</div>--> <!-- end of headerphoto -->
		
            		<div id="nav">
            		<?php 
            			echo $this->navigation()->menu();
            		?>
            		</div> <!-- end of nav -->
				</div><!--end of header-container -->
		</div>
 		
		<?php 
            echo $this->layout()->content;
        ?>
		</div> 
<!-- 		<div id="footer" data-dojo-id="footer" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'bottom', splitter: 'false'"> -->
<!-- 		  <div class="left"> -->
<!-- 		      <span> -->
		          <?php 
// 		              echo $this->appSettings->siteName;
// 		          ?>
<!-- 		      </span> -->
<!-- 		  </div> -->
		  <?php 
// 			 echo $this->copyright();
// 		  ?>
<!-- 		</div> -->
    </div>
</body>
</html>
