<?php

if($this->data instanceof Zend_Paginator) {
    //Zend_Debug::dump($this->data);
    
    if($this->data->count() == 0) {
        echo '<p class="left">There are currently no getaways created for this user.</p>';
        echo '<div class="left">' . $this->button('user-manager', '/admin/user/', array('label' => 'Back To User Manager'), array('class' => 'adminUiButton')) . '</div>';
        
    }
    
    if($this->data->count() > 1) {
        echo $this->paginationControl($this->data, 'Sliding', 'dojo-dropdown-pagination-control.phtml', array('page' => $this->page));
    }

    $this->partialLoop()->setObjectKey('model');

    echo $this->partialLoop('getaways/partials/admin-manage-getaways.phtml', $this->data);

}
