<?php
?>

<ul class="manage-getaways">
<li class="title"><?php echo $this->model->title; ?></li>
<li><?php echo $this->button('edit' . $this->model->id, '/admin/getaways/edit/' . $this->model->id, array('label' => 'Edit Getaway'), array('class' => 'adminUiButton')); ?></li>
<li><?php echo $this->button('delete' . $this->model->id, '/admin/getaways/delete/' . $this->model->id, array('label' => 'Delete Getaway'), array('class' => 'adminUiButton')); ?></li>
</ul>