<?php
	echo $this->doctype();
?>
<html>
<head>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<base href="<?php echo $this->serverUrl($this->baseUrl('/')); ?>" />

<?php

	echo $this->headMeta();
    echo $this->headTitle();
	echo $this->headLink()
                ->prependStylesheet('/lib/dijit/themes/claro/claro.css', 'screen')
                ->headLink()
                ->appendStylesheet('/skins/' . Zend_Registry::get('skinName') . '/style.css', 'screen');
?>
<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:700,300' rel='stylesheet' type='text/css'/>
<script>
dojoConfig = {
	async: true,
	parseOnLoad: true,
	dojoBlankHtmlUrl: "/lib/dojo/resources/blank.html",
	ioPublish: true,
	has: {
       "dojo-firebug": true,
       "dojo-debug-messages": true
	},
	packages: [
	     {
	    	 name: "aurora",
	         location: "/lib/aurora"
	     }
	],
	app: {

	},
	// Get "fresh" resources
	cacheBust: true
};
</script>
<script src="//ajax.googleapis.com/ajax/libs/dojo/1.9.1/dojo/dojo.js"></script>
<script type="text/javascript">
require([
	"aurora/app",
]);
</script>
<?php 
$this->loadMap = false;
if($this->module === 'getaways' && $this->action === 'details') {
$this->loadMap = true;
?>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
  var geocoder;
  var map;
  var address ="<?php echo Zend_Registry::get('getawayAddress');?>";
  
  function initialize() {
    geocoder = new google.maps.Geocoder();
    var latlng = new google.maps.LatLng(-34.397, 150.644);
    var myOptions = {
      zoom: 8,
      center: latlng,
    mapTypeControl: true,
    mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
    navigationControl: true,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    if (geocoder) {
      geocoder.geocode( { 'address': address}, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
          if (status != google.maps.GeocoderStatus.ZERO_RESULTS) {
          map.setCenter(results[0].geometry.location);

            var infowindow = new google.maps.InfoWindow(
                { content: '<b>'+address+'</b>',
                  size: new google.maps.Size(150,50)
                });

            var marker = new google.maps.Marker({
                position: results[0].geometry.location,
                map: map, 
                title:address
            }); 
            google.maps.event.addListener(marker, 'click', function() {
                infowindow.open(map,marker);
            });

          } else {
            alert("No results found");
          }
        } else {
          alert("Geocode was not successful for the following reason: " + status);
        }
      });
    }
  }
</script>
<?php 
}
?>
</head>

<body class="claro" <?php echo $this->loadMap ? ' onload="initialize()"' : '';?>>
	<div data-dojo-type="dijit/layout/LayoutContainer" data-dojo-props="design: 'headline', gutters: 'false'" style="z-index: 0; width: 100%; height: 100%; min-height: 100%;">
	<div data-dojo-id="bodyContentPanel" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', spliter: 'false'" style="padding: 0; margin: 0; min-height: 100%;"> 
		<div id="header" data-dojo-id="header" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', splitter: 'false'">
				<div id="header-container">
				

					<img class="logo" src="<?php echo '/skins/' . Zend_Registry::get('skinName') . '/images/logo_small.png';?>">
					<div class="social-icons">
						<a class="social search" href="#">Search</a>
						<a class="social twitter" href="<?php echo $this->appSettings->twitterUrl; ?>">Twitter</a>
						<a class="social facebook" href="<?php echo $this->appSettings->facebookUrl; ?>">Facebook</a>
					</div> <!-- end of social -->
					
					<!--<div id="headerphoto">-->
					<div id="headerphoto-overlay">
						<?php 
							echo '<img src="' . $this->baseUrl() . '/skins/fypg/images/headerphoto-overlay_small.png" alt="photo" height="393" width="539" />'; 
						?>
					</div> <!-- end of headerphoto-overlay -->
					<!--</div>--> <!-- end of headerphoto -->
		
            		<div id="nav">
            		<?php 
            			echo $this->navigation()->menu();
            		?>
            		</div> <!-- end of nav -->
				</div><!--end of header-container -->
		</div>
		<?php
		 //Zend_Debug::dump(Zend_Registry::get('getawayAddress'));
            echo $this->layout()->content;
        ?>
        <div id="footer">
            <div id="footernav">
							<?php echo $this->navigation()->menu();?>
			</div> <!-- end of footernav -->
		    <div class="clear"></div>
		    <div class="left">
<!-- 		        <span> -->
		            <?php 
// 		                //echo $this->appSettings->siteName;
// 		            ?>
<!-- 		        </span> -->
		   </div>
		  <?php 
			 echo $this->copyright();
		  ?>
		</div>
		</div> 
    </div>
</body>
</html>